syntax = "proto3";

option go_package = "./service";

message RegisterRequest{
    string username = 1;
    string password = 2;
}

message RegisterResponse{
    
}

message LoginRequest{
    string username = 1;
    string password = 2;
}

message LoginResponse{
    string session_id = 1;
}


message Pizza{
    string name = 1;
    string description = 2;
    repeated string ingredients = 3;
    map<string, int64> prices = 4;
}

message MenuRequest{

}

message MenuResponse{
    repeated Pizza menu = 1;
}

message PizzaCreatingRequest{
    Pizza content = 1;
}

message PizzaCreatingResponse{

}

message OrderRequest{
    repeated Pizza content = 1;
    string session_id = 2;
}

message OrderResponse{

}

message GetOrdersRequest{

}

message PizzaOrder{
    Pizza content = 1;
    string status = 2;
    string time = 3;
}

message GetOrdersResponse{
    repeated PizzaOrder list = 1;
    
}

message SessionCheckRequest{
    string session_id = 1;
}

message SessionCheckResponse{
    string username = 1;
}

service UserService{
    rpc Register(RegisterRequest) returns (RegisterResponse);
    rpc Login(LoginRequest) returns (LoginResponse);
    rpc SessionCheck(SessionCheckRequest) returns (SessionCheckResponse);
}

service MenuService{
    rpc GetMenu(MenuRequest) returns (MenuResponse);
    rpc CreatePizza(PizzaCreatingRequest) returns (PizzaCreatingResponse);
}

service OrderService{
    rpc Order(OrderRequest) returns (OrderResponse);
    rpc GetOrders(GetOrdersRequest) returns (GetOrdersResponse);
}